### ISSUE TITLE
Running `example.py` fails with `TypeError: '>=' not supported between instances of 'tuple' and 'float'`

### ISSUE THREAD

**Issue by medikoo** [oliverfei/videocr-PaddleOCR#10]
After successful installation I run `example.py` as is and get the error:

```
% python3.8 example.py                     
[2022/10/26 17:46:34] ppocr DEBUG: Namespace(alpha=1.0, benchmark=False, beta=1.0, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/Users/medikoo/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_box_type='quad', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/Users/medikoo/.paddleocr/whl/det/ch/ch_PP-OCRv3_det_infer', det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, fourier_degree=5, gpu_mem=500, help='==SUPPRESS==', image_dir=None, image_orientation=False, ir_optim=True, kie_algorithm='LayoutXLM', label_list=['0', '180'], lang='ch', layout=True, layout_dict_path=None, layout_model_dir=None, layout_nms_threshold=0.5, layout_score_threshold=0.5, max_batch_size=10, max_text_length=25, merge_no_span_structure=True, min_subgraph_size=15, mode='structure', ocr=True, ocr_order_method=None, ocr_version='PP-OCRv3', output='./output', page_num=0, precision='fp32', process_id=0, re_model_dir=None, rec=True, rec_algorithm='SVTR_LCNet', rec_batch_num=6, rec_char_dict_path='/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paddleocr/ppocr/utils/ppocr_keys_v1.txt', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_model_dir='/Users/medikoo/.paddleocr/whl/rec/ch/ch_PP-OCRv3_rec_infer', recovery=False, save_crop_res=False, save_log_path='./log_output/', scales=[8, 16, 32], ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ser_model_dir=None, show_log=True, sr_batch_num=1, sr_image_shape='3, 32, 128', sr_model_dir=None, structure_version='PP-Structurev2', table=True, table_algorithm='TableAttn', table_char_dict_path=None, table_max_len=488, table_model_dir=None, total_process_num=1, type='ocr', use_angle_cls=False, use_dilation=False, use_gpu=False, use_mp=False, use_npu=False, use_onnx=False, use_pdf2docx_api=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_visual_backbone=True, use_xpu=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=False)
[2022/10/26 17:46:35] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2022/10/26 17:46:35] ppocr DEBUG: dt_boxes num : 2, elapse : 0.0735769271850586
[2022/10/26 17:46:35] ppocr DEBUG: rec_res num  : 2, elapse : 0.33320188522338867
Traceback (most recent call last):
  File "example.py", line 4, in <module>
    save_subtitles_to_file('example_cropped.mp4', 'example.srt', lang='ch', time_start='7:10', time_end='7:34',
  File "/Users/medikoo/Projects/videocr-PaddleOCR/videocr/api.py", line 23, in save_subtitles_to_file
    f.write(get_subtitles(
  File "/Users/medikoo/Projects/videocr-PaddleOCR/videocr/api.py", line 12, in get_subtitles
    v.run_ocr(use_gpu, lang, time_start, time_end, conf_threshold, use_fullframe, brightness_threshold, similar_image_threshold, similar_pixel_threshold, frames_to_skip, crop_x, crop_y, crop_width, crop_height)
  File "/Users/medikoo/Projects/videocr-PaddleOCR/videocr/video.py", line 86, in run_ocr
    predicted_frames = PredictedFrames(i + ocr_start, ocr.ocr(frame), conf_threshold_percent)
  File "/Users/medikoo/Projects/videocr-PaddleOCR/videocr/models.py", line 35, in __init__
    if conf >= conf_threshold:
TypeError: '>=' not supported between instances of 'tuple' and 'float'
```

**Comment by obedabit** [comment]
I am having the same problem

**Comment by oliverfei** [comment]
What PaddleOCR version was this?

**Comment by oliverfei** [comment]
It seems with the latest PaddleOCR version, they changed the prediction data format. I have upgraded the project dependencies and updated the code to account for this.

**Comment by obedabit** [comment]
I guess this was solved after your last commit and you may close this issue
