### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by Soebb** [oliverfei/videocr-PaddleOCR#6]
It looks like some methods used in some of the dependencies is deprecated!
![IMG_20220101_215553_604](https://user-images.githubusercontent.com/87156166/147858053-e60aca69-daf3-41d8-ab81-bd0b10514fb8.jpg)

Python 3.7 (64Bit)
 [My bot repo](https://github.com/Soebb/vse) 

**Edit**: i am trying to fix all errors in my case, and found solutions to fix them except last one(paddleocr).

**Comment by oliverfei** [comment]
Hello, I'm not sure I can do anything in this repo if there is an issue with PaddleOCR. What PaddleOCR version are you using?

**Comment by Soebb** [comment]
Okay.
paddleocr 2.3.0.2

**Comment by oliverfei** [comment]
Does paddleocr 2.3.0.1 also have this issue?

**Comment by Soebb** [comment]
c:\ocr-bot>python37 main.py
C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\.libs\libopenblas.QVLO2T66WEPI7JZ63PS3HMOHFEY472BC.gfortran-win_amd64.dll
C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  stacklevel=1)
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from videocr import save_subtitles_to_file
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\videocr\__init__.py", line 2, in <module>
    from .api import get_subtitles, save_subtitles_to_file
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\videocr\api.py", line 1, in <module>
    from .video import Video
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\videocr\video.py", line 9, in <module>
    from paddleocr import PaddleOCR
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddleocr\__init__.py", line 15, in <module>
    from .paddleocr import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddleocr\paddleocr.py", line 26, in <module>
    from tools.infer import predict_system
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 30, in <module>
    import tools.infer.utility as utility
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddleocr\tools\infer\utility.py", line 23, in <module>
    from paddle import inference
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\__init__.py", line 59, in <module>
    import paddle.dataset  # noqa: F401
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\dataset\__init__.py", line 27, in <module>
    import paddle.dataset.flowers  # noqa: F401
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\dataset\flowers.py", line 39, in <module>
    from paddle.dataset.image import load_image_bytes
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\dataset\image.py", line 51, in <module>
    stderr=subprocess.PIPE)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified





Same error,
Just this time, a bit different.

it seems running with windows give little chance to be workable.

**Comment by oliverfei** [comment]
Hmmm it seems like it might be PaddlePaddle that's giving this error? What version of PaddlePaddle are you using?

**Comment by Soebb** [comment]
Thanks, those errors gones. yes it was because of paddlepaddle (paddlepaddle 2.2.0 no but paddlepaddle 2.0.6 helped)

Just there is an error with paddlepaddle 2.0.6 ([scipy error](https://github.com/scipy/scipy/issues/15254))
that as they announced it fixed in the scipy github version but for installing, it needed python 3.8 not 3.7, so i will try and edit this message soon.
